let firstname = document.getElementById('validationFirstname');
let lastname = document.getElementById('validationLastname');
let birthday = document.getElementById('validationBirthday');
let username = document.getElementById('validationUsername');
let email = document.getElementById('validationEmail');
let address = document.getElementById('validationAddress');
let password1 = document.getElementById('validationPassword1');
let password2 = document.getElementById('validationPassword2');
let city = document.getElementById('validationCity');
let state = document.getElementById('validationState');
let zip = document.getElementById('validationZip');
let submit = document.getElementById('validationSubmit');
let term = document.getElementById('validationTerm');
let cat = document.getElementById('cat');

firstname.addEventListener('click', checkRequired);
firstname.addEventListener('keyup', checkRequired);
lastname.addEventListener('click', checkRequired);
lastname.addEventListener('keyup', checkRequired);
address.addEventListener('click', checkRequired);
address.addEventListener('keyup', checkRequired);
city.addEventListener('click', checkRequired);
city.addEventListener('keyup', checkRequired);
state.addEventListener('click', checkRequired);
state.addEventListener('keyup', checkRequired);
state.addEventListener('change', checkRequired);
zip.addEventListener('click', checkRequired);
zip.addEventListener('keyup', checkRequired);
birthday.addEventListener('click', checkRequired);
birthday.addEventListener('keyup', checkRequired);
birthday.addEventListener('change', checkRequired);
username.addEventListener('click', checkUserName);
username.addEventListener('keyup', checkUserName);
email.addEventListener('click', checkEmail);
email.addEventListener('keyup', checkEmail);
password1.addEventListener('click', checkPassword);
password1.addEventListener('keyup', checkPassword);
password2.addEventListener('click', checkPwdConsistency);
password2.addEventListener('keyup', checkPwdConsistency);
submit.addEventListener('click', checkAll);
cat.addEventListener('dblclick', cheat);

